apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  mykey: cGFzc3dvcmRvcnNvbWV0aGluZw==
---
apiVersion: k8s-rds.io/v1
kind: Database
metadata:
  name: mypgsql
  namespace: default
spec:
  class: db.t3.medium
  engine: aurora-postgresql
  #dbname: mypgsql
  DBInstanceIdentifier: mypgsql-in-dbluster
  name: mypgsql
  password:
    key: mykey
    name: mysecret
  username: postgres
  provider: aws
  #size: 20
  #MaxAllocatedSize: 50
  tags: "environment=test,team=backend"
  skipfinalsnapshot: true
  ApplyImmediately: true
  DBSnapshotIdentifier: "mypgsql-default-1661462171045938588"
  DBClusterIdentifier: "mypgsql-dbluster"
