apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator-service-account.yaml
  - operator-cluster-role.yaml
  - operator-cluster-role-binding.yaml
  - deployment-rbac.yaml

images:
  - name: sorenmat/k8s-rds
    newName: liskl/k8s-rds
    newTag: update-databse-1661429500
